name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build to the `build` branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Build via NPM
        run: |
          npm ci && npm run build
      
      - name: Commit to `build` branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Automatic Build: {msg}"
